spring:
  application:
    name: serviceA

server:
  port: 8081
  servlet-path: /omg

eureka:
  instance:
    metadata-map:
      context-root: ${server.servlet-path:}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/